class StaticPathPlugin {
  // 在构造函数中获取用户给该插件传入的配置
  constructor(options) {}
  // Webpack 会调用 BasicPlugin 实例的 apply 方法给插件实例传入 compiler 对象
  apply(compiler) {
    compiler.plugin('afterEmit', function (compilation) {

      console.log(compilation)
   
      for (var filename in compilation.assets) {
         console.log('@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@',filename)
        
      }
      // compilation.chunks.forEach(function (chunk) {
      //   // 检索由 chunk 生成的每个资源(asset)文件名：
      //   chunk.files.forEach(function (filename) {
      //     // Get the asset source for each file generated by the chunk:
      //     var source = compilation.assets[filename].source();
      //      
      //   });
      // })
    })
  }
}


export default StaticPathPlugin;